name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run check

  unit-and-integration-tests:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit and integration tests with coverage
        run: npm run test:ci
        env:
          NODE_ENV: test

      - name: Check coverage thresholds
        run: |
          echo "Checking coverage thresholds..."
          if [ -f coverage/coverage-summary.json ]; then
            node -e "
              const coverage = require('./coverage/coverage-summary.json');
              const total = coverage.total;
              const statements = total.statements.pct;
              const branches = total.branches.pct;
              const functions = total.functions.pct;
              const lines = total.lines.pct;
              
              console.log('Coverage Summary:');
              console.log('Statements:', statements + '%');
              console.log('Branches:', branches + '%');
              console.log('Functions:', functions + '%');
              console.log('Lines:', lines + '%');
              
              const threshold = 90;
              if (statements < threshold || branches < threshold || functions < threshold || lines < threshold) {
                console.error('Coverage is below 90% threshold');
                process.exit(1);
              }
              console.log('All coverage thresholds met!');
            "
          else
            echo "Coverage summary not found"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Archive coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/
          retention-days: 30

  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Run E2E tests
        run: npm run e2e:ci
        env:
          NODE_ENV: test
          CYPRESS_baseUrl: http://localhost:5000

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7

  accessibility-tests:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run accessibility tests
        run: npm test -- --run tests/ --grep="accessible|accessibility|a11y"
        env:
          NODE_ENV: test

  build:
    runs-on: ubuntu-latest
    needs: [unit-and-integration-tests, e2e-tests]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  notify:
    runs-on: ubuntu-latest
    needs: [unit-and-integration-tests, e2e-tests, accessibility-tests]
    if: always()
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.unit-and-integration-tests.result }}" == "failure" ] || \
             [ "${{ needs.e2e-tests.result }}" == "failure" ] || \
             [ "${{ needs.accessibility-tests.result }}" == "failure" ]; then
            echo "Tests failed!"
            exit 1
          else
            echo "All tests passed!"
          fi
